### ISSUE TITLE
Boolean Indexing support ?

### ISSUE THREAD

**Issue by Ykid** [jjjkkkjjj/Matft#16]
Hi ! Thanks for open sourcing your code. 

Would you mind suggesting the best way to do boolean indexing like numpy ? for example, I can do this in numpy easily

```python
import numpy as np

img = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.uint8)
img[img > 3] = 10
print(img)

# [[ 1  2  3]
# [10 10 10]
# [10 10 10]]
```

I tried to do it element-wise but I found the performance is significantly slower than using Swift Array

```swift
var testing = Array(repeating: 1, count: 160000)
var bar = MfArray(testing, shape: [400,400])
var start = Date()
for i in 0..<400 {
    for j in 0..<400 {
        bar[i,j] = bar[i,j] as! Int + 1
    }
}
print("\(start.timeIntervalSinceNow * -1) seconds elapsed")
//3.706043004989624 seconds elapsed


start = Date()
for i in 0..<400 {
    for j in 0..<400 {
        let index1D = i*400+j
        testing[index1D] = testing[index1D] + 1
    }
}
print("\(start.timeIntervalSinceNow * -1) seconds elapsed")
//0.05165994167327881 seconds elapsed
```

Thanks !

**Comment by jjjkkkjjj** [comment]
Unfortunately Boolean indexing (and fancy indexing) has not been supported yet in Matft.
But fortunately, I found [vdsp function](https://developer.apple.com/documentation/accelerate/1450286-vdsp_vcmprs) to achieve them.

So I’ll try to implement them! So could you wait for a moment?

And the reason of low performance in element-wise operation is n-dimensional array’s data structure. Therefore, for-loop operations in n-dimensional array such like `Matft` and `numpy` tend to be slow. 
So, please convert Swift Array until I implement them;

```swift
var bar = MfArray(testing, shape: [400,400])
let swiftArray = bar.toArray()  as! [[Int]]
for i in 0..<400 {
    for j in 0..<400 {
        bar[i,j] = bar[i,j] + 1
    }
}
```

**Comment by jjjkkkjjj** [comment]
@Ykid 
I've implemented Boolean Indexing!! (but i do not check performance...)
Anyway, you can assign values with boolean like this;

```swift
let img = MfArray([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]], mftype: .UInt8)
img[img > 3] = MfArray([10], mftype: .UInt8)
print(img)
/*
mfarray = 
[[	1,		2,		3],
[	10,		10,		10],
[	10,		10,		10]], type=UInt8, shape=[3, 3]
*/
```

**Comment by Ykid** [comment]
Great thanks ! Let me verify it these days

**Comment by Ykid** [comment]
@jjjkkkjjj The implementation is pretty fast ! 👍
