### ISSUE TITLE
Add fancy indexing

### ISSUE THREAD

**Issue by ALMerrill** [jjjkkkjjj/Matft#17]
Hey, I'm just curious if there are any plans to implement "fancy indexing", where you can pass a list of indeces to an MfArray, and return the items at those indeces, like in numpy. Thanks, its a great library so far.

**Comment by jjjkkkjjj** [comment]
@ALMerrill 
I'd like to implement "fancy indexing", of course.
OK, I'll try to do it on this weekend, but don't expect me excessively! 😅

**Comment by ALMerrill** [comment]
That would be awesome! Whenever you can would be great

**Comment by ALMerrill** [comment]
Also, out of curiosity, is there a way to improve performance with the Boolean indexing? With how I’m using it, it looks like things like `array > someNumber` is taking the majority of the time. I was just curious if you knew of any way to improve performance on calls like that. Thanks so much!

**Comment by jjjkkkjjj** [comment]
> it looks like things like array > someNumber is taking the majority of the time.

Yes, your point is correct. The code to improve performance may be [here](https://github.com/jjjkkkjjj/Matft/blob/04e9ca5a483a794d7511c97d22affeddfb67c2bc/Sources/Matft/core/function/binary_operation.swift#L344) firstly. I think there are much redundant process in this code.

**Comment by jjjkkkjjj** [comment]
Or use boolean as 'storedType' as you pointed out, but this will change many codes...

**Comment by jjjkkkjjj** [comment]
Official code is here; https://github.com/numpy/numpy/blob/cf1306a842d7b1064270bd06951a485121e60816/numpy/core/src/multiarray/mapping.c#L1608

**Comment by jjjkkkjjj** [comment]
@ALMerrill 
I implemented fancy indexing getter!
You can try it by fetching develop branch.
You can pass `MfArray` with Int instead of list to MfArray like this;

```swift
let a = MfArray([[1, 2], [3, 4], [5, 6]])
a[MfArray([0, 1, 2]), MfArray([0, 1, 0])]
/*
mfarray = 
[	1,		4,		5], type=Int, shape=[3]
*/
```

numpy;

```python
>>> x = np.array([[1, 2], [3, 4], [5, 6]])
>>> x[[0, 1, 2], [0, 1, 0]]
array([1, 4, 5])
```

I don't know if I can implement setter...

**Comment by ALMerrill** [comment]
awesome, thank you for the update!

**Comment by jjjkkkjjj** [comment]
@ALMerrill 
I've just implemented fancy setter!!
I didn't check performance, but anyway you can use fancy indexing for `MfArray`🎉

Setter;
```swift
let a = MfArray([[1, 2], [3, 4], [5, 6]])
            
a[MfArray([0, 1, 2]), MfArray([0, -1, 0])] = MfArray([999,888,777])
print(a)
/*
mfarray = 
[[	999,		2],
[	3,		888],
[	777,		6]], type=Int, shape=[3, 2]
*/
            
a.T[MfArray([0, 1, -1]), MfArray([0, 1, 0])] = MfArray([-999,-888,-777])
print(a)
/*
mfarray = 
[[	-999,		-777],
[	3,		-888],
[	777,		6]], type=Int, shape=[3, 2]
*/
```

**Comment by ALMerrill** [comment]
Nice! That's awesome!
