### ISSUE TITLE
Wrong Shape after "ufuncReduce add"

### ISSUE THREAD

**Issue by mlajtos** [jjjkkkjjj/Matft#21]
Hello,

I think there is a bug in `ufuncReduce`. This code

```swift
Matft.ufuncReduce(mfarray: MfArray([1,2,3,4,5,6,7,8,9,10] as [Double]), ufunc: Matft.add)
```
returns

```swift
MfArray([5050, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

I would expect that I would get scalar or array of shape [1]. What am I doing wrong please?

**Comment by jjjkkkjjj** [comment]
Thanks! That's a bug!
I'll fix it.

**Comment by jjjkkkjjj** [comment]
@mlajtos 
Did you update the latest version?
I couldn't reproduce this bug. I got correct `MfArray`;

```swift
print(Matft.ufuncReduce(mfarray: MfArray([1,2,3,4,5,6,7,8,9,10] as [Double]), ufunc: Matft.add))
//mfarray = 
//[	55.0], type=Double, shape=[1]
```

**Comment by mlajtos** [comment]
I am on 0.2.9. Running it inside playground I get this:

<img width="955" alt="Snímka obrazovky 2021-08-09 o 11 07 50" src="https://user-images.githubusercontent.com/1047512/128683288-06021cfa-ce4e-4ea6-93e3-85fa093a226c.png">

**Comment by jjjkkkjjj** [comment]
@mlajtos 
I could reproduce this bug and I've just fixed it.
Your point was correct. Add(binary operation function) seemed to cause this bug.
Could you update the latest commit and check this bug again?

**Comment by mlajtos** [comment]
@jjjkkkjjj I just tried master and it works as expected. Thank you, that was really fast. :)

![IMG_1731](https://user-images.githubusercontent.com/1047512/128715388-079a54cf-d214-4a34-a0fc-4c6d6bd2886c.jpeg)
