### ISSUE TITLE
Matft.math.pow is not working as expected

### ISSUE THREAD

**Issue by slokeshrestha26** [jjjkkkjjj/Matft#22]
Hello, 

Firstly, thank you for working on this! This is really helpful.

Matft.math.pow does not work like np.power(). 

np.power(a,3) raises each element of a to the third power. That is, 

>>> a = np.eye(3) * 3
>>> np.power(a,3)
array([[27.,  0.,  0.],
       [ 0., 27.,  0.],
       [ 0.,  0., 27.]])

The above is returned as a result. 

However, Matft.math.pow takes in a float for the first argument, and a matrix for the second, and behaves as attached following: 

![Screen Shot 2021-09-06 at 3 12 36 PM](https://user-images.githubusercontent.com/35370883/132258233-df1b8e73-a840-46e0-8dd9-22164181b0af.png)
![Screen Shot 2021-09-06 at 3 14 38 PM](https://user-images.githubusercontent.com/35370883/132258321-44789d89-cd94-4a93-8c87-893c8e7e03e8.png)

**Comment by jjjkkkjjj** [comment]
Thank you for reporting!

Maybe, you can use `bases` as first argument not `base`.

`Matft.math.power` can receive both `Float` and `MfArray` and have 2 arguments which are `base(s)` and `exponent(s)`.
Therefore, `Matft.math.power` discriminates between `Float` and `MfArray` by a singular form (=`base` or `exponent`) or plural form (=`bases` or `exponents`). 

So, to reproduce `np.power(a,3)`;

```swift
let a = Matft.eye(dim: 3) * 3
print(Matft.math.power(bases: a, exponent: 3)) // <=== Check both arguments !!
```

But as you pointed out, this is too confusing, so I'll integrate these arguments forms into a specific form.
