### ISSUE TITLE
Adding demo for image processing

### ISSUE THREAD

**Issue by franva** [jjjkkkjjj/Matft#26]
Hi jjjkkkjjj,

Great work on bring Numpy to Swift!!!

I am learning how to do inference within CoreML using Swift.

So far I have gotten the UIImage from an image picker and I need to do preprocessing
e.g. resize, transpose, normalize(mean=(0,0,0), std=(1,1,1))

And after hours and hours searching, Swift just proofed that it is not a language which is friendly for image processing.
And I found your Repo here which has all the amazing feature I need.

So I think it is very helpful if you could add a demo for this.

Cheers

**Comment by jjjkkkjjj** [comment]
The above code's problem has some problems.
- Multiple type conversion (UInt8 -> Float(MfArray), Float(MfArray) -> UInt8)
- The code is not understandable...
  - example: `arr.withDataUnsafeMBPtrT(datatype: Float.self)`

The second point may be solved by the [next protocol version](https://github.com/jjjkkkjjj/Matft/tree/ver3)(Readme was not updated).

**Comment by jjjkkkjjj** [comment]
Hi @franva
I've just implemented conversion functions (`Matft.image.cgimage2mfarray` and `Matft.image.mfarray2cgimage`)
So, you can process image as mfarray!

Examples are below;

```swift
@IBOutlet weak var originalImageView: UIImageView!
@IBOutlet weak var reverseImageView: UIImageView!
@IBOutlet weak var swapImageView: UIImageView!

func reverse(){
    var image = Matft.image.cgimage2mfarray(self.reverseImageView.image!.cgImage!)

    // reverse
    image = image[~<<-1]
    self.reverseImageView.image = UIImage(cgImage: Matft.image.mfarray2cgimage(image))
}


func swapchannel(){
    var image = Matft.image.cgimage2mfarray(self.swapImageView.image!.cgImage!)

    // swap channel
    //image = image[0~<, 0~<, MfArray([1,0,2,3])] // not supported
    image = image.swapaxes(axis1: 0, axis2: -1)[MfArray([1,0,2,3])].swapaxes(axis1: 0, axis2: -1)
    self.swapImageView.image = UIImage(cgImage: Matft.image.mfarray2cgimage(image))
}
```

<img width="513" alt="image-processing" src="https://user-images.githubusercontent.com/16914891/176985133-fd4a1cfb-029a-42e9-be6d-778f4c181f1f.png">

Please refer to the example [here](./MatftDemo/MatftDemo/ViewController.swift).
