### ISSUE TITLE
Support for atan2

### ISSUE THREAD

**Issue by kkaun** [jjjkkkjjj/Matft#27]
Thanks for great library!

Is there any way to get `atan2` from combining 2 `MfArray`s? Like this:

```
let R = MfArray([a, b ,c])

let x = atan2((R[2, 1], R[2, 2])
```

The issue for us is that we're porting the code from numpy logic, and functionality like that is supported there. E.g. we can retrieve single `Double` from the expression like `R[2, 1]` so we're struggling now on how to get similar behaviour.

Thanks in advance!

**Comment by jjjkkkjjj** [comment]
Thank you for your feedback!
Fortunately, `atan2` implementation may be easy for me if i use the [`vvatan2`](https://developer.apple.com/documentation/accelerate/1470446-vvatan2) in accelerate framework.
So, wait for a moment!

**Comment by jjjkkkjjj** [comment]
@kkaun 
I've just implemented `arctan2` like [`numpy.arctan2`](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html)!
Check the latest Matft!

**Comment by kkaun** [comment]
@jjjkkkjjj thank you very much!
