### ISSUE TITLE
Subscript bug using `Matft.arange()`

### ISSUE THREAD

**Issue by nnethery** [jjjkkkjjj/Matft#38]
Numpy version
``` python
a = np.zeros([88, 2, 2])
b = np.zeros([32, 88, 2])
print(a[np.arange(88), b[0, :, 0].astype(int), 0].shape) # Outputs to (88,)
```
Matft version
``` swift
let a = Matft.nums(0, shape: [88, 2, 2])
let b = Matft.nums(0, shape: [32, 88, 2]).astype(.Int)
print(a[Matft.arange(start: 0, to: 88, by: 1), b[0, Matft.all, 0], 0].shape) // Outputs to [88, 88]
```

According to Numpy the shape of the MfArray should be `[88]`, not `[88, 88]`.

**Comment by jjjkkkjjj** [comment]
@nnethery 
Thank you for reporting the bug. I misunderstood the fancy indexing rule...
Can you explain why this operation returned the shape as (88,)?
I misunderstood the returned array's shape will be same as the shape combined by all input's shape. For the example you mentioned, input indexing array's shapes are (88,)=`np.arange(88)`, (88,)=`b[0, :, 0].astype(int)`, (0=scalar,). So, returned shape will be (88, 88, 0) = (88,88) by combining the input indexing array's shapes.

**Comment by jjjkkkjjj** [comment]
Ah, I may understand.
The input indexing shape will be broadcasted.

```python
>>> np.arange(8).reshape(4,2)[[2,3], [0,2,1]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 
```

**Comment by jjjkkkjjj** [comment]
@nnethery 
I've just fixed this bug!
Please check it again/

**Comment by nnethery** [comment]
> @nnethery I've just fixed this bug! Please check it again.

It works great. You rock @jjjkkkjjj  🎉!
