### ISSUE TITLE
How to get the content of the MfArray?

### ISSUE THREAD

**Issue by Ykid** [jjjkkkjjj/Matft#46]
Hi I'm trying to get the values inside the MfArray by indexing. The usage is similar to the [`item` method](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.item.html) of numpy. Wondering what is the best way to do it?

```swift
var a = MfArray([[1,2,3], [4, 5, 6]], mftype: .Int32)
a[0, 0] as! Int //works

a = MfArray([1,2,3], mftype: .Int32)
a[0] as! Int //doesn't work. I can do a[0][0][0][0][0][0][0] for infinite number of times
```

For now I'm converting the MfArray to Array and get the first element as work around

Thanks in advance!

**Comment by jjjkkkjjj** [comment]
Yes, `MfArray` conforms to Collection protocol ([here](https://github.com/jjjkkkjjj/Matft/blob/cc52eca30f35a5743eb3c476ba9a475c41ce99cd/Sources/Matft/core/general/collection.swift#L4)).
So, If you use the subscription operation to pass "a" integer, return `MfArray`.
I've implemented workaround function named `item`. Please update master branch and use it!

```swift
  let a = Matft.arange(start: 0, to: 27, by: 1, shape: [27])
  print(a[0])
  /*
  0 // a[0] is MfArray!! Nevertheless, The scalar is printed (I don't know why...)
  */
  print(a[0] + 4)
  /*
  mfarray = 
  [    4], type=Int, shape=[1]
  */
  
  // Workaround
  print(a.item(index: 0, type: Int.self))
  /*
  0
  */
  print(a.item(index: 0, type: Int.self) + 4)
  /*
  4
  */
  ```

**Comment by Ykid** [comment]
Thank you!

**Comment by bunnyhero** [comment]
Will you be updating the Cocoapod with this workaround in it?
