### ISSUE TITLE
Tips to convert an MfArray to MLMultiArray

### ISSUE THREAD

**Issue by Ykid** [jjjkkkjjj/Matft#48]
Could you kindly inform me if there is a way to convert `MfArray` to `MLMultiArray` , as I have found [a method to convert the latter to the former](https://github.com/jjjkkkjjj/Matft/blob/88572d78a808962c6001eb529b38c3927fe5a56f/Sources/Matft/core/object/mfarray.swift#L120) but I am uncertain if there is a similar method for the reverse operation. If such a method doesn't exists, could you please recommend the most effective/performant approach for accomplishing this?

My current approach is

```swift
extension MfArray {
    func toMLMultiArray() throws -> MLMultiArray {
        guard let array = self.astype(.Float).flatten().toArray() as? [Float] else {
              //throw some errors here
        }
        let arrShape = self.shape
        let mlShapedArray: MLShapedArray<Float> = MLShapedArray(scalars: array, shape: arrShape)
        return MLMultiArray(mlShapedArray)
    }
}
```

Thanks in advance!

**Comment by jjjkkkjjj** [comment]
@Ykid 
Sorry for too late response.
I found the solution in the `MLMultiArray`‘s [initializer](https://developer.apple.com/documentation/coreml/mlmultiarray/2881219-init).
Fortunately MfArray (MfData) has a dataPointer as UnsafeMutableRawPointer [here](https://github.com/jjjkkkjjj/Matft/blob/88572d78a808962c6001eb529b38c3927fe5a56f/Sources/Matft/core/object/mfdata.swift#L20C1-L20C1).
So, we can convert MfArray into MLMultiArray like this;

```swift
let a = MfArray…
MLMultiArray(dataPointer: a.mfdata.data_real, shape: a.shape.map{ NSNumber($0) }, strides: a.strides.map{ NSNumber($0) }, dataType: Float.self)
```

**Comment by Ykid** [comment]
Thank you @jjjkkkjjj for the answer!

**Comment by jjjkkkjjj** [comment]
@Ykid I've just added conversion method you wanted.
Try it like this;

```swift
let a = MfAarray...
let mlmultiarray = a.toMLMultiArray()
```
