### ISSUE TITLE
Boolean indexing doesnt support equality?

### ISSUE THREAD

**Issue by darwinharianto** [jjjkkkjjj/Matft#49]
let img = MfArray([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]], mftype: .UInt8)
img[img == 3]

this throws
Referencing operator function '==' on 'BinaryInteger' requires that 'MfArray' conform to 'BinaryInteger'

**Comment by jjjkkkjjj** [comment]
Could you try 
/

**Comment by jjjkkkjjj** [comment]
@darwinharianto 
Could you try `===` instead of `==`?
